name: ape_store
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: any
  flutter_inappwebview: ^5.0.0
  loading_animation_widget: any
  url_launcher: any
  rename: any
  liquid_pull_to_refresh: 3.0.1
  connectivity_plus: 4.0.2
  lottie: 2.6.0
  dotlottie_loader: 0.0.3
  gap: 3.0.1
  flutter: 
    sdk: flutter
  firebase_core: ^2.24.2
  onesignal_flutter: ^5.1.0
  flutter_native_splash: ^2.4.0

dev_dependencies: 
  flutter_lints: any
  flutter_launcher_icons: "^0.13.1"
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_solid.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  

