name: silver_view
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: any
  flutter_inappwebview: ^5.3.2
  loading_animation_widget: any
  url_launcher: any
  rename: any
  liquid_pull_to_refresh: 3.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: any
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

